on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@latest
    - name: uninstall
      run: make uninstall
    - name: buildx
      run: make buildx
    - name: install
      run: make install
    - name: uninstall
      run: make uninstall
    - name: docker clean
      run: docker system prune -a
    timeout-minutes: 30