on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: uninstall
      run: make uninstall
    - name: buildx
      run: make buildx
    - name: install
      run: make install
    - name: test
      run: make helmtest
    - name: uninstall
      run: make uninstall
    - name: 
    - name: docker clean
      run: docker system prune -a
    timeout-minutes: 10