on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: uninstall-test
      run: make uninstall-test
    - name: buildx
      run: make buildx
    - name: kubetest
      run: make kubetest
    - name: upgrade-prod
      run: make upgrade-prod
    - name: logs
      run: make logs
      if: always()
    - name: docker clean
      run: make clean
      if: always()
    timeout-minutes: 10